apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

images:
  - name: sample-app
    newName: ghcr.io/fveim/devopsproject
    newTag: latest

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: prod
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: sample-app
